### ISSUE TITLE
Copy authorized_keys to container

### ISSUE THREAD

**Issue by zulli73** [b3vis/borg-server#2]
This is in part a question and a proposal to improve docs. As an occasional Docker user, it took me some time to successfully copy the 'authorized_keys' file to the container. In the end, what caused troubles to me was the user ownership - but it took me some time to figure that out. While I know have a working solution, I wonder whether there's a better way of doing it, thus this issue. Here's what I do:
```
# Create a 'storage volume'
docker volume create --name borg-keys-storage

# Create container using the just created volume
docker create \
--name=borg-server \
--restart=always \
--volume borg-keys-storage:/home/borg/.ssh \
-v /home:/backups \
-p 22:22 \
b3vis/borg-server

# Prepare public keys...
cat ~/.ssh/id_rsa.pub > /tmp/authorized_keys
# Adjust user to 1000, as that's the UID of user 'borg' (see Dockerfile of borg-server image)
sudo chown 1000 /tmp/authorized_keys
# And copy it to the container (and thus into the 'storage volume')
docker cp /tmp/authorized_keys borg-server:/home/borg/.ssh
```

**Comment by b3vis** [comment]
Hi,

Thanks for the notes. I would personally enter the container and create the authorized_keys file as the Borg user.

Try: docker exec -it borg-server sh 

Where borg-server is the name of your container.

Kind regards,
b3vis
